/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateRouteImport } from './routes/create'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as EditNoteIdRouteImport } from './routes/edit.$noteId'
import { Route as ViewNoteIdRouteImport } from './routes/view.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const EditNoteIdRoute = EditNoteIdRouteImport.update({
  id: '/edit/$noteId',
  path: '/edit/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewNoteIdRoute = ViewNoteIdRouteImport.update({
  id: '/view/$noteId',
  path: '/view/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$noteId': typeof EditNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$noteId': typeof EditNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit/$noteId': typeof EditNoteIdRoute
  '/view/$noteId': typeof ViewNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$noteId'
    | '/view/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$noteId'
    | '/view/$noteId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/sign-in'
    | '/sign-up'
    | '/edit/$noteId'
    | '/view/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EditNoteIdRoute: typeof EditNoteIdRoute
  ViewNoteIdRoute: typeof ViewNoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/$noteId': {
      id: '/edit/$noteId'
      path: '/edit/$noteId'
      fullPath: '/edit/$noteId'
      preLoaderRoute: typeof EditNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$noteId': {
      id: '/view/$noteId'
      path: '/view/$noteId'
      fullPath: '/view/$noteId'
      preLoaderRoute: typeof ViewNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EditNoteIdRoute: EditNoteIdRoute,
  ViewNoteIdRoute: ViewNoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
