/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCreateRouteImport } from './routes/_authed/create'
import { Route as AuthedEditNoteIdRouteImport } from './routes/_authed/edit.$noteId'
import { Route as AuthedViewNoteIdRouteImport } from './routes/_authed/view.$noteId'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedEditNoteIdRoute = AuthedEditNoteIdRouteImport.update({
  id: '/edit/$noteId',
  path: '/edit/$noteId',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedViewNoteIdRoute = AuthedViewNoteIdRouteImport.update({
  id: '/view/$noteId',
  path: '/view/$noteId',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/create': typeof AuthedCreateRoute
  '/edit/$noteId': typeof AuthedEditNoteIdRoute
  '/view/$noteId': typeof AuthedViewNoteIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/create': typeof AuthedCreateRoute
  '/': typeof AuthedIndexRoute
  '/edit/$noteId': typeof AuthedEditNoteIdRoute
  '/view/$noteId': typeof AuthedViewNoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/edit/$noteId': typeof AuthedEditNoteIdRoute
  '/_authed/view/$noteId': typeof AuthedViewNoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/create'
    | '/edit/$noteId'
    | '/view/$noteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/create'
    | '/'
    | '/edit/$noteId'
    | '/view/$noteId'
  id:
    | '__root__'
    | '/_authed'
    | '/sign-in'
    | '/sign-up'
    | '/_authed/create'
    | '/_authed/'
    | '/_authed/edit/$noteId'
    | '/_authed/view/$noteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/edit/$noteId': {
      id: '/_authed/edit/$noteId'
      path: '/edit/$noteId'
      fullPath: '/edit/$noteId'
      preLoaderRoute: typeof AuthedEditNoteIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/view/$noteId': {
      id: '/_authed/view/$noteId'
      path: '/view/$noteId'
      fullPath: '/view/$noteId'
      preLoaderRoute: typeof AuthedViewNoteIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedEditNoteIdRoute: typeof AuthedEditNoteIdRoute
  AuthedViewNoteIdRoute: typeof AuthedViewNoteIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedEditNoteIdRoute: AuthedEditNoteIdRoute,
  AuthedViewNoteIdRoute: AuthedViewNoteIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
